version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/skillswap
      - PORT=3000
    depends_on:
      - mongo
      - solana

  solana:
    build:
      context: ./contracts
      dockerfile: Dockerfile
    ports:
      - "8899:8899"
    environment:
      - SOLANA_URL=http://localhost:8899

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
